Default config:
 Simulation name: sim1
 Model name: skeleton
 Controller name: rlsVelocity
 Debug mode: false

# smiyahara: controller の config の場所は要検討
Simulation config:
 Solver:
  Control input: velocity

 Controller:
  Flag: false ## smiyahara: 未実装
  Dynamics: false
  Work: skeleton

 Graph:
  Flag: true
  Make gp: true
  Sampling time: 10

 Gif:
  Flag: false
  Sampling time: 100
  Link color: grey
  Joint color: black
  Out:
   Terminal: true
   Dir: true
  Plane:
   y-z:
    Flag: true
    x min: -0.5
    x max: 0.5
    y min: -0.5
    y max: 0.5
   x-z:
    Flag: true
    x min: -0.5
    x max: 0.5
    y min: -0.5
    y max: 0.5
   x-y:
    Flag: true
    x min: -0.5
    x max: 0.5
    y min: -0.5
    y max: 0.5
   3D:
    Flag: false
    x min: -0.5
    x max: 0.5
    y min: -0.5
    y max: 0.5
    z min: -0.5
    z max: 0.5

 Choreonoid:
  Flag: true
  Sampling time: 10