materials:
  -
    name: Default
  -
    name: Ground
  -
    name: Ice

contactMaterials:
  -
    materials: [ Default, Default ]
    friction: 10.
  -
    materials: [ Default, Ice ]
    friction: 0.0
