materials:
  -
    name: Default
  -
    name: Body
  -
    name: Ground
  -
    name: Ice

contactMaterials:
  -
    materials: [ Default, Default ]
    friction: 10.
  -
    materials: [ Body, Ground ]
    friction: 10.
  -
    materials: [ Default, Ground ]
    friction: 10.
  -
    materials: [ Default, Ice ]
    friction: 0.0
